name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd sales-marketing-analytics
            git pull origin main
            docker build -t fastapi-app .
            docker stop $(docker ps -q --filter "ancestor=fastapi-app") || true
            docker run -d -p 8000:8000 fastapi-app
